spring:
  profiles: prod

  server:
    port: 8081

  data:
    elasticsearch:
      zaodao:
        cluster-name: es-cluster
        cluster-nodes: 114.67.239.37:50005,114.67.239.37:50003
        client-transport-sniff: false
        client-ignore-cluster-name: false
        client-ping-timeout: 10s
        client-nodes-sampler-interval: 10s
  dubbo:
     config:
        application-name: es-dubbo-provider
        registry-address: 192.168.1.219:2181
        registry-protocol: zookeeper
        registry-id: zookeeper
        protocol-name: dubbo
        protocol-port: 40012